#include "config.h"
#include <assert.h>
#include <bitcoin/chainparams.h>
#include <ccan/array_size/array_size.h>
#include <ccan/err/err.h>
#include <common/setup.h>
#include <stdio.h>
#include <string.h>

/* AUTOGENERATED MOCKS START */
/* AUTOGENERATED MOCKS END */

/* The identity constants of doc/blake2b-chain-identity.md.
 *
 * chain_hash is deliberately absent: it is the genesis hash both chains share,
 * so there is nothing here to get wrong. What is here is the invoice prefix,
 * which is the only thing in a BOLT 11 string that says which chain it is for,
 * and the prefix each network carried before, which decoding still accepts.
 */
static const struct {
	const char *network;
	const char *lightning_hrp;
	const char *legacy_lightning_hrp;
	u32 activation_height;
} expected[] = {
	{"bitcoin", "blake", "bc", 961640},
	{"regtest", "blakert", "bcrt", 0},
	{"signet", "tbsblake", "tbs", 0},
	{"testnet4", "tblake", "tb", 0},
	/* testnet3 shares testnet4's old prefix and is not a chain this fork
	 * runs on, so it keeps what upstream gave it. */
	{"testnet", "tb", NULL, 0},
};

int main(int argc, char *argv[])
{
	common_setup(argv[0]);

	for (size_t i = 0; i < ARRAY_SIZE(expected); i++) {
		const struct chainparams *p
			= chainparams_for_network(expected[i].network);
		assert(p);

		assert(streq(p->lightning_hrp, expected[i].lightning_hrp));

		if (expected[i].legacy_lightning_hrp) {
			assert(p->legacy_lightning_hrp);
			assert(streq(p->legacy_lightning_hrp,
				     expected[i].legacy_lightning_hrp));
			/* A legacy prefix that equals the current one would
			 * mean the network never moved, and would make the
			 * "is this for another chain" message nonsense. */
			assert(!streq(p->legacy_lightning_hrp,
				      p->lightning_hrp));
		} else {
			assert(!p->legacy_lightning_hrp);
		}

		assert(p->blake2b_activation_height
		       == expected[i].activation_height);
	}

	/* The prefix has to be reachable by name, since that is how an invoice
	 * is routed to a network when it is decoded. */
	for (size_t i = 0; i < ARRAY_SIZE(expected); i++) {
		const struct chainparams *p
			= chainparams_by_lightning_hrp(expected[i].lightning_hrp);
		assert(p);
		assert(streq(p->network_name, expected[i].network));
	}

	/* A prefix a network used to carry must still resolve, because stored
	 * records were written with it. The bookkeeper decodes its own history
	 * with no chain check, and refusing those loses accounting data for
	 * every payment made before the upgrade: that is what this missed the
	 * first time, and only Core Lightning's own test suite caught it. */
	for (size_t i = 0; i < ARRAY_SIZE(expected); i++) {
		const struct chainparams *p;

		if (!expected[i].legacy_lightning_hrp)
			continue;

		p = chainparams_by_lightning_hrp(
			expected[i].legacy_lightning_hrp);
		assert(p);
	}

	/* And a prefix still in use wins over one that was retired. testnet3
	 * uses "tb" today and testnet4 used to, so a lookup of "tb" has to be
	 * testnet3's rather than whichever the table lists first. */
	assert(streq(chainparams_by_lightning_hrp("tb")->network_name,
		     "testnet"));
	assert(streq(chainparams_by_lightning_hrp("tblake")->network_name,
		     "testnet4"));

	/* And no two networks may claim the same prefix, or an invoice would
	 * decode to whichever came first in the table. */
	for (size_t i = 0; i < ARRAY_SIZE(expected); i++) {
		for (size_t j = i + 1; j < ARRAY_SIZE(expected); j++) {
			assert(!streq(expected[i].lightning_hrp,
				      expected[j].lightning_hrp));
		}
	}

	/* The activation height is what the gossip rule compares against, so
	 * it must be set on the chain that changed its proof of work and left
	 * alone everywhere else: a floor on a chain that never moved would
	 * refuse every announcement there is. */
	assert(chainparams_for_network("bitcoin")->blake2b_activation_height
	       == 961640);
	assert(chainparams_for_network("regtest")->blake2b_activation_height
	       == 0);

	common_shutdown();

	return 0;
}
