#include "config.h"
#include <assert.h>
#include <bitcoin/chainparams.h>
#include <common/setup.h>
#include <stdio.h>

/* AUTOGENERATED MOCKS START */
/* AUTOGENERATED MOCKS END */

/* The proof of work changed at this block; the chain did not. */
#define BLAKE2B_ACTIVATION 961640

int main(int argc, char *argv[])
{
	const struct chainparams *main;
	struct bitcoin_blkid genesis;

	common_setup(argv[0]);
	main = chainparams_for_network("bitcoin");
	assert(main);

	/* Gossip for channels funded before activation is ignored: that output
	 * exists for nodes which did not upgrade too, and its spend may happen
	 * where this node cannot see it. */
	assert(main->when_lightning_became_cool == BLAKE2B_ACTIVATION);

	/* chain_hash stays Bitcoin's genesis.  This is Bitcoin; only the proof
	 * of work changed, so the network is not given an identity of its own. */
	assert(bitcoin_blkid_from_hex("000000000019d6689c085ae165831e93"
				      "4ff763ae46a2a6c172b3f1b60a8ce26f",
				      64, &genesis));
	assert(bitcoin_blkid_eq(&main->genesis_blockhash, &genesis));

	printf("when_lightning_became_cool = %u, chain_hash unchanged\n",
	       main->when_lightning_became_cool);
	common_shutdown();
	return 0;
}
