#include "config.h"
#include "../blake2b.c"
#include "../block.c"
#include "../psbt.c"
#include "../shadouble.c"
#include "../signature.c"
#include "../tx.c"
#include "../varint.c"
#include <assert.h>
#include <common/setup.h>
#include <stdio.h>

/* AUTOGENERATED MOCKS START */
/* AUTOGENERATED MOCKS END */

/* From src/test/data/block_header_v2.json in the BLAKE2b hardfork tree: the
 * cross-implementation vectors for the redesigned header, covering all four
 * ASIC layouts and the XOR mask boundaries.  Each is a bare header with an
 * empty transaction list appended. */
static const struct {
	const char *name;
	const char *block;
	const char *blkid;
	u32 timestamp;
} vectors[] = {
	{
		"profile_0_time_offset",
		"000000a01f1e1d1c1b1a191817161514131211100f0e0d0c0b0a090807060504"
		"0302010000112233445566778899aabbccddeeff00102030405060708090a0b0"
		"c0d0e0f0a8913577ffff001d0df0ad0b44332211efcdab89ffeeddccbbaa9988"
		"77665544332211005802000003001c0000000000000000000000000000000000"
		"40d10c008967452301efcdab8967452301efcdab8967452301efcdab89674523"
		"01efcdab"
		/* no transactions */ "00",
		"4b495dcf05d70a49785b799b22284fbcd9dd1209237c53c87e4674b15587d704",
		2000000000
	},
	{
		"profile_1_time_offset_nonzero_key",
		"000000a01f1e1d1c1b1a191817161514131211100f0e0d0c0b0a090807060504"
		"0302010000112233445566778899aabbccddeeff00102030405060708090a0b0"
		"c0d0e0f0a8913577ffff001d0df0ad0b44332211efcdab89ffeeddccbbaa9988"
		"77665544332211005802000001001d00efcdab8967452301efcdab8967452301"
		"41d10c008967452301efcdab8967452301efcdab8967452301efcdab89674523"
		"01efcdab"
		/* no transactions */ "00",
		"44b383821dea9af8d7d81ba7741c34ac8c07ab81ab081d8b6bf0575a787a1eef",
		2000000000
	},
	{
		"profile_2_time_offset_selector_7",
		"000000a01f1e1d1c1b1a191817161514131211100f0e0d0c0b0a090807060504"
		"0302010000112233445566778899aabbccddeeff00102030405060708090a0b0"
		"c0d0e0f0a8913577ffff001d0df0ad0bddccbbaaefcdab89ffeeddccbbaa9988"
		"77665544332211005802000003001e071032547698badcfe1032547698badcfe"
		"40d10c008967452301efcdab8967452301efcdab8967452301efcdab89674523"
		"01efcdab"
		/* no transactions */ "00",
		"06fddae4eaca10b85c87a3c7ed71717fd83998a32fe13f4780722b1f5d882e76",
		2000000000
	},
	{
		"profile_3_time_offset_selector_8",
		"000000a01f1e1d1c1b1a191817161514131211100f0e0d0c0b0a090807060504"
		"0302010000112233445566778899aabbccddeeff00102030405060708090a0b0"
		"c0d0e0f0a8913577ffff001d0df0ad0b44332211040302010000000000000000"
		"ffffffffffffffff5802000003001f081032547698badcfe1032547698badcfe"
		"40d10c008967452301efcdab8967452301efcdab8967452301efcdab89674523"
		"01efcdab"
		/* no transactions */ "00",
		"e6304527536f619d3ad71b1c21a22fdef9068498acc561b4100b034373a87058",
		2000000000
	},
	{
		"profile_0_time_offset_disabled_selector_255",
		"000000a01f1e1d1c1b1a191817161514131211100f0e0d0c0b0a090807060504"
		"0302010000112233445566778899aabbccddeeff00102030405060708090a0b0"
		"c0d0e0f000943577ffff001dffffffff44332211efcdab89ffeeddccbbaa9988"
		"776655443322110088776655030018ff22222222222222221111111111111111"
		"40d10c0000000000000000000000000000000000000000000000000000000000"
		"00000000"
		/* no transactions */ "00",
		"c31b24420d67f86e524f980a24a18e88f36c821046d5288251b5d88998c69f86",
		2000000000
	},
};

int main(int argc, char *argv[])
{
	common_setup(argv[0]);

	for (size_t i = 0; i < ARRAY_SIZE(vectors); i++) {
		struct bitcoin_block *b;
		struct bitcoin_blkid blkid;
		char hex[hex_str_size(sizeof(blkid))];

		b = bitcoin_block_from_hex(tmpctx, chainparams_for_network("regtest"),
					   vectors[i].block,
					   strlen(vectors[i].block));
		assert(b);
		assert(b->hdr.header_v2);
		assert(b->hdr.timestamp == vectors[i].timestamp);

		bitcoin_block_blkid(b, &blkid);
		assert(bitcoin_blkid_to_hex(&blkid, hex, sizeof(hex)));
		if (!streq(hex, vectors[i].blkid)) {
			fprintf(stderr, "%s: got %s, expected %s\n",
				vectors[i].name, hex, vectors[i].blkid);
			abort();
		}
	}

	/* A truncated v2 header must be rejected, not read past. */
	assert(!bitcoin_block_from_hex(tmpctx,
				       chainparams_for_network("regtest"),
				       vectors[0].block,
				       strlen(vectors[0].block) - 20));

	common_shutdown();
	return 0;
}
